#ifndef CONFIG_H
#define CONFIG_H

#define PROJECT "@PROJECT@"

#define PANTOMIME_VERSION "@PROJECT_VERSION@"

#define PANTOMIME_VERSION_MAJOR "@PROJECT_VERSION_MAJOR@"

#define PANTOMIME_VERSION_MINOR "@PROJECT_VERSION_MINOR@"

#define PANTOMIME_VERSION_PATCH "@PROJECT_VERSION_PATCH@"

#endif
